# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    pip3 install "ansible==2.9.17"
  displayName: 'InstallAnsible'

- script: |
    pip3 install ansible[azure]
  displayName: 'Install Ansible rm module'

- script: |
    ansible-playbook create-web-app.yml
  displayName: 'Run Ansible Playbook'
  env:
   AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
   AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
   AZURE_SECRET: $(AZURE_SECRET) 
   AZURE_TENANT: $(AZURE_TENANT)

  


